@startuml

:Executor: -- (Execute task)
:Executor: -- (Generate task)
:Operation package: - (Execute task)
:Operation package: - (Publish data)
(Generate task) ..> (Evaluate resources): <<include>>
(Generate task) ..> (Evaluate dependencies): <<include>>
(Generate task) ..> (Control compute and input resources): <<include>>
(Execute task) ..> (Control compute and input resources): <<include>>
(Evaluate dependencies) ..> (Place data): <<include>>
(Publish data) ..> (Place data): <<include>>
(Publish data) -> (Generate task)
:Managed data: - (Place data)

@enduml

@startuml
:Executor: -- (Execute task)

(Create local node handle)

(Register checkpointed entity)

@enduml